// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvsLcet_WtpDac_VVrfDCp43iEVijLxjs',
    appId: '1:3582344596:web:46a069a919a599cda76381',
    messagingSenderId: '3582344596',
    projectId: 'pokedexflutter-baba5',
    authDomain: 'pokedexflutter-baba5.firebaseapp.com',
    storageBucket: 'pokedexflutter-baba5.appspot.com',
    measurementId: 'G-EVT8YXH7MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2LHSHgq2hqM8uov8Kchmy8Q_nXXT_ap4',
    appId: '1:3582344596:android:df31992560a9ef15a76381',
    messagingSenderId: '3582344596',
    projectId: 'pokedexflutter-baba5',
    storageBucket: 'pokedexflutter-baba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKB_cB15evWOLsQsy2l9NBoOI10Ppw-fg',
    appId: '1:3582344596:ios:d08328b7b79c0e34a76381',
    messagingSenderId: '3582344596',
    projectId: 'pokedexflutter-baba5',
    storageBucket: 'pokedexflutter-baba5.appspot.com',
    iosClientId: '3582344596-nlgjbgh0cb325oat4b6v73u5d6rp6mge.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKB_cB15evWOLsQsy2l9NBoOI10Ppw-fg',
    appId: '1:3582344596:ios:1c2f94e763db93f8a76381',
    messagingSenderId: '3582344596',
    projectId: 'pokedexflutter-baba5',
    storageBucket: 'pokedexflutter-baba5.appspot.com',
    iosClientId: '3582344596-8bajigaihmgvt0qkt3j92hhmn3932qrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}